---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app01
spec:
  serviceAccountName: my-service-account
  replicas: 1
  selector:
    matchLabels:
      app: my-app01
  template:
    metadata:
      labels:
        app: my-app01
    spec:
      containers:
        - name: my-app01
          image: acrdemo202322.azurecr.io//mcr.microsoft.com/dotnet/aspnet
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: my-app01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
